// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbt5hs27ZKzHlMuSk17RlRQNwMlu0cOLg',
    appId: '1:500239611373:web:175abcfc362e8cd44e23e4',
    messagingSenderId: '500239611373',
    projectId: 'parking-app-capstone',
    authDomain: 'parking-app-capstone.firebaseapp.com',
    databaseURL: 'https://parking-app-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'parking-app-capstone.appspot.com',
    measurementId: 'G-N0E7XQCLQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Pb0fjo_p7A3I6qZzi7PzkWTeRZ3cTOM',
    appId: '1:500239611373:android:877b9eab4f779a5e4e23e4',
    messagingSenderId: '500239611373',
    projectId: 'parking-app-capstone',
    databaseURL: 'https://parking-app-capstone-default-rtdb.firebaseio.com',
    storageBucket: 'parking-app-capstone.appspot.com',
  );
}
